### ISSUE TITLE
Idea: Wouldn't be nicer to put everything under one repository?

### ISSUE THREAD

**Issue by octoper** [lanvard/foundation#29]
Hello @reindert-vetter, wouldn't be nicer to have everything under one repository like [Laravel Framework](https://github.com/laravel/framework/) repo so it's easier to manage and contribute?

**Comment by reindert-vetter** [comment]
You are right. I struggled a lot with it. Previously I had even many more repositories. I can imagine that if you make a package for Confetti, you only need support, contract and error. But I indeed think it's better to put everything under 1 repository.

**Comment by octoper** [comment]
If you want any help I can help you with that!

**Comment by reindert-vetter** [comment]
That would be great! You can move everything to confetti-framework/framework. I've added you with extra permissions. I will withdraw it after after a few months of inactivity.

**Comment by reindert-vetter** [comment]
I think it's good to archive the old repositories for the time being

**Comment by octoper** [comment]
Yeah we should, but we need to decide how we will proceed with the versioning of the modules that have been moved into the framework repo!

**Comment by reindert-vetter** [comment]
This is indeed a big breaking change. As far as I know nobody uses Confetti in production. Since we are still in version 0, I feel free to make these kinds of fundamental adjustments. We do need to properly document what the user has to adjust to use the new version. Because we have to test it first you can use tag v0.29.0-beta (in a separated branch). If anyone has code from version 0.28.0, it will still works for them.

**Comment by octoper** [comment]
I have made both repositories but the `framework` repo is not yet finished. I have to make the GitHub actions for testing and formatting.

**Comment by reindert-vetter** [comment]
Okay, everything looks good! Let me know if you need help with anything.
